
// ********RoostGPT********
/*
Test generated by RoostGPT for test Java-09-Jan using AI Type Claude AI and AI Model claude-sonnet-4-20250514

ROOST_METHOD_HASH=findAll_e3226f7b62
ROOST_METHOD_SIG_HASH=findAll_a2bf6614ea

Scenario 1: Return All Products When Repository Contains Multiple Products

Details:
  TestName: findAllReturnsAllProductsWhenRepositoryContainsMultipleProducts
  Description: This test verifies that the findAll method returns a complete list containing all products stored in the repository when multiple products exist. It ensures that no products are missed and all stored products are included in the returned list.

Execution:
  Arrange: Create a ProductRepository instance which will be initialized with sample data through the constructor (Laptop, Mouse, Keyboard, Monitor, Headphones).
  Act: Call the findAll() method on the repository instance.
  Assert: Verify that the returned list is not null, has a size of 5 (matching the number of products initialized in constructor), and contains all expected product names.

Validation:
  This assertion verifies that the findAll method successfully retrieves all products from the internal ConcurrentHashMap and converts them into an ArrayList. The test is significant because it ensures that the basic retrieval functionality works correctly and that all stored data is accessible through this method, which is fundamental for displaying product catalogs in the application.

Scenario 2: Return Empty List When Repository Contains No Products

Details:
  TestName: findAllReturnsEmptyListWhenRepositoryIsEmpty
  Description: This test checks that the findAll method returns an empty list when the repository contains no products. It validates the method's behavior in edge cases where the data store is empty.

Execution:
  Arrange: Create a ProductRepository instance and clear all products from the internal map using deleteById for each existing product to simulate an empty repository state.
  Act: Call the findAll() method on the empty repository.
  Assert: Verify that the returned list is not null and has a size of 0 (empty list).

Validation:
  This assertion ensures that the method handles empty repository scenarios gracefully by returning an empty list rather than null or throwing an exception. This is crucial for preventing null pointer exceptions in client code and maintaining consistent API behavior regardless of the repository state.

Scenario 3: Return Independent Copy of Products List

Details:
  TestName: findAllReturnsIndependentCopyOfProductsList
  Description: This test verifies that the findAll method returns a new ArrayList instance that is independent of the internal storage, ensuring that modifications to the returned list do not affect the repository's internal state.

Execution:
  Arrange: Create a ProductRepository instance with default sample data.
  Act: Call findAll() method twice to get two separate list instances, then modify one of the returned lists by adding a new product or clearing it.
  Assert: Verify that the two returned lists are different object instances, and that modifications to one list do not affect the other list or subsequent calls to findAll().

Validation:
  This assertion confirms that the method creates a defensive copy of the data, which is essential for maintaining data integrity and preventing external code from accidentally modifying the repository's internal state. This encapsulation principle is critical for thread safety and data consistency in concurrent environments.

Scenario 4: Return Correct Product Objects With All Properties

Details:
  TestName: findAllReturnsProductsWithCorrectProperties
  Description: This test ensures that the findAll method returns Product objects with all their properties intact and correctly populated, verifying that the data integrity is maintained during the retrieval process.

Execution:
  Arrange: Create a ProductRepository instance which initializes with known sample products.
  Act: Call the findAll() method to retrieve all products.
  Assert: Verify that each returned Product object contains the expected values for name, description, price, and stock properties by checking specific products like "Laptop" with price "999.99" and stock 15.

Validation:
  This assertion validates that the method not only returns the correct number of products but also ensures that each Product object maintains its complete state and properties. This is vital for ensuring that business logic depending on product properties functions correctly throughout the application.

Scenario 5: Maintain Thread Safety During Concurrent Access

Details:
  TestName: findAllMaintainsThreadSafetyDuringConcurrentAccess
  Description: This test verifies that the findAll method operates safely in a multi-threaded environment, ensuring that concurrent calls to findAll do not interfere with each other or cause data corruption.

Execution:
  Arrange: Create a ProductRepository instance and set up multiple threads that will simultaneously call the findAll method.
  Act: Execute multiple threads concurrently, each calling findAll() method multiple times.
  Assert: Verify that all threads complete successfully without exceptions, and that each thread receives consistent results with the expected number of products.

Validation:
  This assertion ensures that the use of ConcurrentHashMap in the underlying implementation provides the necessary thread safety for read operations. This test is crucial for applications that may have multiple users or processes accessing product data simultaneously, ensuring data consistency and preventing race conditions.

Scenario 6: Return Products After Repository Modifications

Details:
  TestName: findAllReturnsUpdatedProductsAfterRepositoryModifications
  Description: This test checks that the findAll method reflects the current state of the repository after products have been added, updated, or deleted, ensuring that the method always returns the most up-to-date product list.

Execution:
  Arrange: Create a ProductRepository instance with initial sample data, then perform modifications such as adding a new product using save() method and deleting an existing product using deleteById().
  Act: Call findAll() method after the modifications.
  Assert: Verify that the returned list reflects the changes made to the repository, containing the newly added product and not containing the deleted product.

Validation:
  This assertion confirms that the findAll method provides a real-time view of the repository state, which is essential for ensuring that users always see the current product inventory. This behavior is critical for e-commerce applications where product availability and catalog updates need to be immediately visible to users.

*/

// ********RoostGPT********

package com.example.demo.repository;

import com.example.demo.model.Product;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.springframework.boot.test.context.SpringBootTest;
import java.math.BigDecimal;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicInteger;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.stereotype.Repository;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

@SpringBootTest
public class ProductRepositoryFindAllTest {

	private ProductRepository productRepository;

	@BeforeEach
	void setUp() {
		productRepository = new ProductRepository();
	}

	@Test
	@Tag("valid")
	void findAllReturnsAllProductsWhenRepositoryContainsMultipleProducts() {
		// Act
		List<Product> products = productRepository.findAll();
		// Assert
		assertNotNull(products);
		assertEquals(5, products.size());

		boolean hasLaptop = products.stream().anyMatch(p -> "Laptop".equals(p.getName()));
		boolean hasMouse = products.stream().anyMatch(p -> "Mouse".equals(p.getName()));
		boolean hasKeyboard = products.stream().anyMatch(p -> "Keyboard".equals(p.getName()));
		boolean hasMonitor = products.stream().anyMatch(p -> "Monitor".equals(p.getName()));
		boolean hasHeadphones = products.stream().anyMatch(p -> "Headphones".equals(p.getName()));

		assertTrue(hasLaptop);
		assertTrue(hasMouse);
		assertTrue(hasKeyboard);
		assertTrue(hasMonitor);
		assertTrue(hasHeadphones);
	}

	@Test
	@Tag("boundary")
	void findAllReturnsEmptyListWhenRepositoryIsEmpty() {
		// Arrange - Clear all products
		List<Product> initialProducts = productRepository.findAll();
		for (Product product : initialProducts) {
			productRepository.deleteById(product.getId());
		}
		// Act
		List<Product> products = productRepository.findAll();
		// Assert
		assertNotNull(products);
		assertEquals(0, products.size());
		assertTrue(products.isEmpty());
	}

	@Test
	@Tag("valid")
	void findAllReturnsIndependentCopyOfProductsList() {
		// Act
		List<Product> firstCall = productRepository.findAll();
		List<Product> secondCall = productRepository.findAll();
		// Assert
		assertNotNull(firstCall);
		assertNotNull(secondCall);
		assertNotSame(firstCall, secondCall);
		assertEquals(firstCall.size(), secondCall.size());
		// Modify first list
		firstCall.clear();
		// Verify second list is unaffected
		assertEquals(5, secondCall.size());

		// Verify subsequent calls are unaffected
		List<Product> thirdCall = productRepository.findAll();
		assertEquals(5, thirdCall.size());
	}

	@Test
	@Tag("valid")
	void findAllReturnsProductsWithCorrectProperties() {
		// Act
		List<Product> products = productRepository.findAll();
		// Assert
		assertNotNull(products);
		assertEquals(5, products.size());
		Product laptop = products.stream().filter(p -> "Laptop".equals(p.getName())).findFirst().orElse(null);
		assertNotNull(laptop);
		assertEquals("Laptop", laptop.getName());
		assertEquals("High-performance laptop", laptop.getDescription());
		assertEquals(new BigDecimal("999.99"), laptop.getPrice());
		assertEquals(15, laptop.getStock());
		Product mouse = products.stream().filter(p -> "Mouse".equals(p.getName())).findFirst().orElse(null);
		assertNotNull(mouse);
		assertEquals("Mouse", mouse.getName());
		assertEquals("Wireless mouse", mouse.getDescription());
		assertEquals(new BigDecimal("29.99"), mouse.getPrice());
		assertEquals(50, mouse.getStock());
	}

	@Test
	@Tag("integration")
	void findAllMaintainsThreadSafetyDuringConcurrentAccess() throws InterruptedException {
		// Arrange
		int threadCount = 10;
		int callsPerThread = 100;
		ExecutorService executor = Executors.newFixedThreadPool(threadCount);
		CountDownLatch latch = new CountDownLatch(threadCount);
		AtomicInteger successCount = new AtomicInteger(0);
		AtomicInteger errorCount = new AtomicInteger(0);
		// Act
		for (int i = 0; i < threadCount; i++) {
			executor.submit(() -> {
				try {
					for (int j = 0; j < callsPerThread; j++) {
						List<Product> products = productRepository.findAll();
						assertNotNull(products);
						assertEquals(5, products.size());
						successCount.incrementAndGet();
					}
				}
				catch (Exception e) {
					errorCount.incrementAndGet();
				}
				finally {
					latch.countDown();
				}
			});
		}
		latch.await();
		executor.shutdown();
		// Assert
		assertEquals(threadCount * callsPerThread, successCount.get());
		assertEquals(0, errorCount.get());
	}

	@Test
	@Tag("valid")
	void findAllReturnsUpdatedProductsAfterRepositoryModifications() {
		// Arrange - Initial state
		List<Product> initialProducts = productRepository.findAll();
		assertEquals(5, initialProducts.size());
		// Add a new product
		Product newProduct = new Product("Tablet", "10-inch tablet", new BigDecimal("299.99"), 10);
		Product savedProduct = productRepository.save(newProduct);
		// Delete an existing product
		Product productToDelete = initialProducts.get(0);
		productRepository.deleteById(productToDelete.getId());
		// Act
		List<Product> updatedProducts = productRepository.findAll();
		// Assert
		assertNotNull(updatedProducts);
		assertEquals(5, updatedProducts.size()); // 5 initial - 1 deleted + 1 added = 5
		boolean hasNewProduct = updatedProducts.stream().anyMatch(p -> "Tablet".equals(p.getName()));
		assertTrue(hasNewProduct);
		boolean hasDeletedProduct = updatedProducts.stream().anyMatch(p -> p.getId().equals(productToDelete.getId()));
		assertFalse(hasDeletedProduct);
	}

}