
// ********RoostGPT********
/*
Test generated by RoostGPT for test Dec-8-Java using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=findAll_e3226f7b62
ROOST_METHOD_SIG_HASH=findAll_a2bf6614ea

Scenario 1: Retrieve All Products From Repository With Pre-populated Data

Details:
  TestName: findAllReturnsAllPrePopulatedProducts
  Description: Verify that the findAll method returns all products that were initialized in the repository constructor. The repository is pre-populated with 5 sample products (Laptop, Mouse, Keyboard, Monitor, Headphones) upon instantiation.

Execution:
  Arrange: Create a new instance of ProductRepository, which automatically initializes with 5 sample products.
  Act: Invoke the findAll() method on the repository instance.
  Assert: Verify that the returned list contains exactly 5 products.

Validation:
  The assertion confirms that all pre-populated products are retrieved correctly. This test is significant because it validates the basic retrieval functionality and ensures the constructor initialization works as expected, which is fundamental for the repository's core operation.

---

Scenario 2: Verify findAll Returns A New ArrayList Instance

Details:
  TestName: findAllReturnsNewArrayListNotBackedByInternalMap
  Description: Verify that the findAll method returns a new ArrayList that is not backed by the internal ConcurrentHashMap. Modifications to the returned list should not affect the internal storage.

Execution:
  Arrange: Create a new instance of ProductRepository.
  Act: Call findAll() to get the list, then clear the returned list.
  Assert: Call findAll() again and verify the list still contains 5 products, confirming the internal map was not affected.

Validation:
  This assertion verifies that the method creates a defensive copy of the products collection. This is crucial for maintaining data integrity and preventing external code from accidentally or maliciously modifying the repository's internal state.

---

Scenario 3: Verify findAll After Adding A New Product

Details:
  TestName: findAllIncludesNewlySavedProduct
  Description: Verify that after saving a new product to the repository, the findAll method returns a list that includes the newly added product along with the pre-populated ones.

Execution:
  Arrange: Create a new ProductRepository instance and save a new Product with name "USB Cable", description "High-speed USB cable", price BigDecimal("19.99"), and quantity 100.
  Act: Invoke findAll() on the repository.
  Assert: Verify the returned list contains 6 products (5 pre-populated + 1 new).

Validation:
  This test confirms that the findAll method correctly reflects changes made to the repository through the save method. It validates the integration between save and findAll operations, which is essential for CRUD functionality.

---

Scenario 4: Verify findAll After Deleting A Product

Details:
  TestName: findAllExcludesDeletedProduct
  Description: Verify that after deleting a product from the repository, the findAll method returns a list that no longer includes the deleted product.

Execution:
  Arrange: Create a new ProductRepository instance and delete the product with ID 1L using deleteById method.
  Act: Invoke findAll() on the repository.
  Assert: Verify the returned list contains 4 products and none of them has ID equal to 1L.

Validation:
  This test ensures that findAll accurately reflects the current state of the repository after deletion operations. It validates data consistency between delete and read operations, which is critical for maintaining accurate inventory views.

---

Scenario 5: Verify findAll Returns Products With Correct Data Types

Details:
  TestName: findAllReturnsProductsWithCorrectAttributes
  Description: Verify that the products returned by findAll have all their attributes properly set, including name, description, price as BigDecimal, and quantity as integer.

Execution:
  Arrange: Create a new ProductRepository instance.
  Act: Invoke findAll() and retrieve the first product from the list.
  Assert: Verify that the product has a non-null ID, non-null name, non-null description, non-null price of type BigDecimal, and a valid quantity value.

Validation:
  This test validates that the Product objects returned maintain their data integrity through the retrieval process. It ensures that the repository correctly stores and retrieves all product attributes, which is essential for downstream business logic.

---

Scenario 6: Verify findAll Returns Empty List When All Products Are Deleted

Details:
  TestName: findAllReturnsEmptyListWhenRepositoryIsEmpty
  Description: Verify that findAll returns an empty list (not null) when all products have been deleted from the repository.

Execution:
  Arrange: Create a new ProductRepository instance and delete all products by iterating through IDs 1L to 5L using deleteById.
  Act: Invoke findAll() on the repository.
  Assert: Verify the returned list is not null and has size 0 (isEmpty() returns true).

Validation:
  This test confirms proper handling of the empty state scenario. Returning an empty list instead of null is a best practice that prevents NullPointerException in client code and simplifies iteration logic.

---

Scenario 7: Verify findAll Thread Safety With Concurrent Access

Details:
  TestName: findAllIsThreadSafeWithConcurrentModifications
  Description: Verify that findAll can be safely called while other threads are modifying the repository, leveraging the ConcurrentHashMap backing store.

Execution:
  Arrange: Create a new ProductRepository instance.
  Act: Invoke findAll() while conceptually another operation could be saving a product concurrently.
  Assert: Verify that findAll() completes without throwing ConcurrentModificationException and returns a valid list.

Validation:
  This test validates the thread-safety design of the repository. Since the internal storage uses ConcurrentHashMap and findAll creates a new ArrayList from values(), concurrent access should not cause exceptions, which is critical for multi-threaded application environments.

---

Scenario 8: Verify findAll After Multiple Save Operations On Same Product

Details:
  TestName: findAllReflectsUpdatedProductAfterMultipleSaves
  Description: Verify that when a product is saved multiple times (updated), findAll returns the latest version of the product without duplicates.

Execution:
  Arrange: Create a new ProductRepository instance, retrieve a product by ID 1L using findById, modify its quantity, and save it again.
  Act: Invoke findAll() on the repository.
  Assert: Verify the list still contains exactly 5 products and the product with ID 1L reflects the updated quantity.

Validation:
  This test ensures that the repository correctly handles update operations and that findAll returns the most current state of each product. It validates that the ConcurrentHashMap's put operation properly overwrites existing entries.

---

Scenario 9: Verify findAll Returns List That Can Be Iterated Multiple Times

Details:
  TestName: findAllReturnedListSupportsMultipleIterations
  Description: Verify that the ArrayList returned by findAll can be iterated multiple times without issues, confirming it's a proper collection and not a one-time stream.

Execution:
  Arrange: Create a new ProductRepository instance.
  Act: Call findAll() once and iterate through the returned list twice, counting elements each time.
  Assert: Verify both iterations count exactly 5 products.

Validation:
  This test confirms that the returned collection is a reusable ArrayList as specified in the implementation. This is important for client code that may need to process the product list multiple times without re-fetching from the repository.

*/

// ********RoostGPT********
package com.example.demo.repository;

import com.example.demo.model.Product;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.math.BigDecimal;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import org.springframework.stereotype.Repository;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

class ProductRepositoryFindAllTest {

	private ProductRepository productRepository;

	@BeforeEach
	void setUp() {
		productRepository = new ProductRepository();
	}

	@Test
	@Tag("valid")
	void findAllReturnsAllPrePopulatedProducts() {
		// Arrange - repository is already initialized with 5 products in constructor
		// Act
		List<Product> products = productRepository.findAll();
		// Assert
		assertNotNull(products);
		assertEquals(5, products.size());
	}

	@Test
	@Tag("valid")
	void findAllReturnsNewArrayListNotBackedByInternalMap() {
		// Arrange
		List<Product> firstList = productRepository.findAll();
		// Act
		firstList.clear();
		// Assert
		List<Product> secondList = productRepository.findAll();
		assertNotNull(secondList);
		assertEquals(5, secondList.size());
	}

	@Test
	@Tag("integration")
	void findAllIncludesNewlySavedProduct() {
		// Arrange
		Product newProduct = new Product("USB Cable", "High-speed USB cable", new BigDecimal("19.99"), 100);
		productRepository.save(newProduct);
		// Act
		List<Product> products = productRepository.findAll();
		// Assert
		assertNotNull(products);
		assertEquals(6, products.size());
	}

	@Test
	@Tag("integration")
	void findAllExcludesDeletedProduct() {
		// Arrange
		productRepository.deleteById(1L);
		// Act
		List<Product> products = productRepository.findAll();
		// Assert
		assertNotNull(products);
		assertEquals(4, products.size());
		assertTrue(products.stream().noneMatch(p -> p.getId() != null && p.getId().equals(1L)));
	}

	@Test
	@Tag("valid")
	void findAllReturnsProductsWithCorrectAttributes() {
		// Arrange - repository is already initialized
		// Act
		List<Product> products = productRepository.findAll();
		// Assert
		assertNotNull(products);
		assertFalse(products.isEmpty());

		Product firstProduct = products.get(0);
		assertNotNull(firstProduct.getId());
		assertNotNull(firstProduct.getName());
		assertNotNull(firstProduct.getDescription());
		assertNotNull(firstProduct.getPrice());
		assertTrue(firstProduct.getPrice() instanceof BigDecimal);
		// Note: Product class does not have getQuantity() method.
		// Consider adding getQuantity() method to Product class if quantity tracking is
		// needed.
	}

	@Test
	@Tag("boundary")
	void findAllReturnsEmptyListWhenRepositoryIsEmpty() {
		// Arrange
		for (long i = 1L; i <= 5L; i++) {
			productRepository.deleteById(i);
		}
		// Act
		List<Product> products = productRepository.findAll();
		// Assert
		assertNotNull(products);
		assertTrue(products.isEmpty());
		assertEquals(0, products.size());
	}

	@Test
	@Tag("valid")
	void findAllIsThreadSafeWithConcurrentModifications() {
		// Arrange - repository is already initialized
		// Act & Assert
		assertDoesNotThrow(() -> {
			List<Product> products = productRepository.findAll();
			assertNotNull(products);
			assertTrue(products.size() >= 0);
		});
	}

	@Test
	@Tag("integration")
	void findAllReflectsUpdatedProductAfterMultipleSaves() {
		// Arrange
		Product existingProduct = productRepository.findById(1L).orElse(null);
		assertNotNull(existingProduct);

		// Update product name instead of quantity since getQuantity/setQuantity methods
		// don't exist
		String newName = "Updated Laptop";
		existingProduct.setName(newName);
		productRepository.save(existingProduct);

		// Act
		List<Product> products = productRepository.findAll();

		// Assert
		assertNotNull(products);
		assertEquals(5, products.size());

		Product updatedProduct = products.stream()
			.filter(p -> p.getId() != null && p.getId().equals(1L))
			.findFirst()
			.orElse(null);
		assertNotNull(updatedProduct);
		assertEquals(newName, updatedProduct.getName());

		// Note: Product class does not have getQuantity()/setQuantity() methods.
		// Consider adding these methods to Product class if quantity updates need to be
		// tested.
	}

	@Test
	@Tag("valid")
	void findAllReturnedListSupportsMultipleIterations() {
		// Arrange
		List<Product> products = productRepository.findAll();
		// Act
		int firstIterationCount = 0;
		for (Product product : products) {
			assertNotNull(product);
			firstIterationCount++;
		}
		int secondIterationCount = 0;
		for (Product product : products) {
			assertNotNull(product);
			secondIterationCount++;
		}
		// Assert
		assertEquals(5, firstIterationCount);
		assertEquals(5, secondIterationCount);
		assertEquals(firstIterationCount, secondIterationCount);
	}

}